<?xml version="1.0"?>
<robot name="CrustCrawler" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="M_pi" value="3.1415" />
  <xacro:property name="LinkWidth" value="0.025" />
  <xacro:property name="LinkHeight" value="0.02" />

  <xacro:property name="offset" value="0.0" />

  <xacro:property name="MotorWidth" value="0.04" />
  <xacro:property name="MotorLength" value="0.055" />
  <xacro:property name="MotorOffset" value="0.04" />

  <xacro:property name="BaseWidth" value="0.15" />

  <xacro:property name="L0" value="0.01" />
  <xacro:property name="L1" value="0.055" />
  <xacro:property name="L2" value="0.22" />
  <xacro:property name="L3" value="0.15" />
  <xacro:property name="Lp" value="0.0" />


  <xacro:property name="Lc" value="0.02895" />
  <xacro:property name="Lc2" value="0.17433" />
  <xacro:property name="Lc3" value="0.12078" />
  <xacro:property name="d3" value="-0.003" />


  <xacro:property name="m1" value="0.1874" />
  <xacro:property name="m2" value="0.17226" />
  <xacro:property name="m3" value="0.18391" />
  <xacro:property name="mp" value="0.0" />


  <!-- Gazebo -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/crustcrawler</robotNamespace>
    </plugin>

    <plugin name="gazebo_plugin" filename="libgazebo_plugin.so">
    </plugin>

  </gazebo>

  <gazebo reference="link1">
    <selfCollide>true</selfCollide>
  </gazebo>
  <gazebo reference="link2">
    <selfCollide>true</selfCollide>
  </gazebo>
  <gazebo reference="link3">
    <selfCollide>true</selfCollide>
  </gazebo>
  <gazebo reference="gripper_left">
    <selfCollide>true</selfCollide>
  </gazebo>
  <gazebo reference="gripper_right">
    <selfCollide>true</selfCollide>
  </gazebo>


  <!-- links, joints and transmissions -->


  <link name="world"/>

  <joint name="world_base" type="fixed">
    <parent link="world"/>
    <child link="base"/>
    <origin xyz = "0 0 0.15" />
  </joint>

  <!-- base link -->

  <link name="base">
    <collision>
      <origin xyz="0 0 -0.015" rpy="0 0 0"/>
      <geometry>
	       <box size="${BaseWidth} ${BaseWidth} 0.01"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${-L1/2}" rpy="0 0 0"/>
      <geometry>
         <mesh filename="package://crustcrawler_description/meshes/Base.STL"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m1}"/>
      <inertia
	  ixx="0.0" ixy="0.0" ixz="0.0"
	  iyy="0.0" iyz="0.0"
	  izz="0.0"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <axis xyz="0 0 1"/>
    <!--limit effort="1000.0" lower="${-M_pi}" upper="${M_pi}" velocity="0.5"/ -->
    <parent link="base"/>
    <child link="link1"/>
    <origin xyz="0 0 0" rpy= "0 0 0"/>
    <dynamics damping="0.7" friction="0.1"/>
  </joint>


  <!-- link 1 -->

  <link name="link1">
    <collision>
      <origin xyz="0 0 ${L1 / 2}" rpy="0 0 0"/>
      <geometry>
        <box size="${MotorWidth} ${MotorLength} ${L1*1.5}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${-L1/2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://crustcrawler_description/meshes/Link1.STL"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${Lc}" rpy="0 0 0"/>
      <mass value="${m1}"/>
      <inertia
    	  ixx="0.0001130151" ixy="-0.00000860914" ixz="0.00000048865"
    	                     iyy="0.00008504653"  iyz="-0.00000210564"
    	                                          izz="0.0001180217"/>
    </inertial>
  </link>



  <joint name="joint2" type="continuous">
    <origin xyz="0 0 ${L1}" rpy="${-M_pi / 2} 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="link1"/>
    <child link="link2"/>
    <dynamics damping="0.7" friction="0.1"/>
  </joint>

  <!-- link 2 -->
  <link name="link2">
    <collision>
      <origin xyz="${L2/2 - MotorOffset/2} 0 0" rpy="0 0 0"/>
      <geometry>
         <box size=" ${L2 - MotorOffset*3} ${LinkWidth} ${LinkHeight}"/>
      </geometry>
    </collision>

    <collision>
      <origin xyz = "${L2 - 0.015} 0 0" />
      <geometry>
         <box size=" ${0.05} ${MotorWidth} ${MotorLength}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 -0.002" rpy="${M_pi/2} ${-M_pi/2} ${M_pi/2}"/>
      <geometry>
	       <mesh filename="package://crustcrawler_description/meshes/Link2.STL"/> <!--<box size="${L2} ${LinkWidth} ${LinkWidth}"/>-->
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${Lc2} 0 0" rpy="0 0 0"/>
      <mass value="${m2}"/>
      <inertia
	  ixx="0.00006763106" ixy="0.000003336"  ixz="-0.00000058233"
                        iyy="0.0006261946" iyz="0.00000477121"
	                                         izz="0.000635118"/>
    </inertial>
  </link>



  <joint name="joint3" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${L2} 0 0" rpy="0 0 0"/>
    <dynamics damping="0.7" friction="0.1"/>
  </joint>


  <!-- link 3 -->


  <link name="link3">
    <collision>
      <origin xyz="${L3/2} 0 ${d3}" rpy="0 0 0"/>
      <geometry>
        <box size=" ${L3 - MotorOffset*2} ${LinkWidth/2} ${LinkHeight}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="${L3 - 0.01} 0 ${d3}" rpy="0 0 0"/>
      <geometry>
        <box size=" ${0.045} ${MotorLength/2} ${MotorWidth*2 - 0.005}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${M_pi/2} ${-M_pi/2} ${M_pi/2}"/>
      <geometry>
        <mesh filename="package://crustcrawler_description/meshes/Link3.STL"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${Lc3} 0 0 " rpy="0 0 0"/>
      <mass value="${m3}"/>
      <inertia
    ixx="0.00009477987" ixy="0.00000560523" ixz="0.00000272008"
                        iyy="0.0003202224"  iyz="0.00000034515"
                                            izz="0.0002467779"/>
    </inertial>
  </link>


  <joint name="joint4" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="link3"/>
    <child link="gripper_left"/>
    <origin xyz="${L3 - 0.003} 0 0.016" rpy="${M_pi/2} 0 0"/>
    <dynamics damping="0.7" friction="0.1"/>
  </joint>

  <joint name="joint5" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="link3"/>
    <child link="gripper_right"/>
    <origin xyz="${L3 - 0.003} 0.003 -0.023" rpy="${M_pi/2} 0 0"/>
    <dynamics damping="0.7" friction="0.1"/>
  </joint> -->

  <!-- left gripper -->

  <link name="gripper_left">
    <collision>
      <origin xyz="0 0 0" rpy="${M_pi} 0 0"/>
      <geometry>
        <mesh filename="package://crustcrawler_description/meshes/Grip.STL"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${M_pi} 0 0"/>
      <geometry>
        <mesh filename="package://crustcrawler_description/meshes/Grip.STL"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0 " rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia
    ixx="0.0" ixy="0.0" ixz="0.0"
    iyy="0.0" iyz="0.0"
    izz="0.0"/>
    </inertial>
  </link>

  <!-- right gripper -->

  <link name="gripper_right">
    <collision>
      <origin xyz="0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://crustcrawler_description/meshes/Grip.STL"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://crustcrawler_description/meshes/Grip.STL"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0 " rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia
    ixx="0.0" ixy="0.0" ixz="0.0"
    iyy="0.0" iyz="0.0"
    izz="0.0"/>
    </inertial>
  </link>



</robot>
